// Sample data — financial analyst / consulting scenario
window.SAMPLE_TAGS = [
  { name: "Q3-25", color: "blue" },
  { name: "Q4-25", color: "blue" },
  { name: "TechCorp", color: "violet" },
  { name: "ClientA", color: "violet" },
  { name: "MeridianCap", color: "violet" },
  { name: "DCF", color: "amber" },
  { name: "Comps", color: "amber" },
  { name: "Memo", color: "green" },
  { name: "Earnings", color: "green" },
  { name: "Sector/Semis", color: "rose" },
  { name: "Sector/SaaS", color: "rose" },
  { name: "Internal", color: "gray" },
];

window.SAMPLE_NOTES = [
  {
    id: "N-0142",
    title: "TechCorp Q3-25 — Earnings Review",
    type: "analysis",
    tags: ["Q3-25", "TechCorp", "Earnings", "Sector/Semis"],
    pinned: true,
    updated: "2026-05-15T14:32:08",
    created: "2026-05-14T09:11:00",
    author: "ML",
    wordCount: 1842,
    actionItems: [
      { id: "a1", text: "Update DCF terminal growth to 2.5%", done: false, due: "2026-05-17", owner: "ML" },
      { id: "a2", text: "Send revised PT memo to PM by EOD", done: false, due: "2026-05-16", owner: "ML" },
      { id: "a3", text: "Pull guidance commentary from transcript p.14", done: true, due: "2026-05-15", owner: "ML" },
    ],
    body: [
      { type: "h1", text: "TechCorp Q3-25 — Earnings Review" },
      { type: "meta", text: "Reported 14-May-2026 AMC · Conference call 17:00 ET · Ticker TCRP" },
      { type: "h2", text: "Headline" },
      { type: "p", text: "Beat on revenue (+3.2% vs cons), miss on GM (-110bps). Mgmt guided Q4 below street on softer hyperscaler capex. Stock down 6% AH — overdone. Maintain BUY, lowering PT from $182 → $174." },
      { type: "h2", text: "The print" },
      { type: "table", columns: ["Metric", "Actual", "Cons.", "Δ", "YoY"], rows: [
        ["Revenue ($M)", "4,820", "4,670", "+150", "+12.4%"],
        ["Gross profit ($M)", "2,892", "2,898", "-6", "+9.8%"],
        ["Opex ($M)", "1,640", "1,615", "+25", "+11.0%"],
        ["EBIT ($M)", "1,252", "1,283", "-31", "+8.2%"],
        ["EPS ($)", "1.42", "1.39", "+0.03", "+11.0%"],
      ], sumCols: [1, 2, 3] },
      { type: "h2", text: "Why GM compressed" },
      { type: "ul", items: [
        "Mix shift — H100 → H200 transition; lower-margin SKU heavier in Q3",
        "FX headwind ~30bps (JPY weakness vs guide)",
        "Higher CoWoS packaging costs persist — capacity still tight",
      ]},
      { type: "callout", tone: "warn", text: "Watch CoWoS unlock in Q1-26. If pricing power persists, GM recovery to 61% is achievable. If not, sector multiple compression risk." },
      { type: "h2", text: "Valuation" },
      { type: "p", text: "DCF: WACC 9.2%, terminal growth 2.5% (revised down from 3.0%). Implied EV $1.42T → $1.36T. See [[DCF Model Assumptions — Semis FY26]]." },
      { type: "code", lang: "python", text: "# revised terminal growth\nWACC = 0.092\ng_terminal = 0.025  # was 0.030\nFCF_2030 = 142_400  # USD M\nTV = FCF_2030 * (1 + g_terminal) / (WACC - g_terminal)\nprint(f'TV = ${TV/1e6:.2f}T')" },
    ],
  },
  {
    id: "N-0141",
    title: "Meridian Cap — Discovery Call Notes",
    type: "meeting",
    tags: ["MeridianCap", "ClientA", "Internal"],
    pinned: true,
    updated: "2026-05-15T11:04:22",
    created: "2026-05-15T10:30:00",
    author: "ML",
    wordCount: 612,
    actionItems: [
      { id: "b1", text: "Share sector comp deck (Semis + SaaS)", done: false, due: "2026-05-17", owner: "ML" },
      { id: "b2", text: "Intro Sara to coverage team", done: false, due: "2026-05-18", owner: "JK" },
    ],
    body: [
      { type: "h1", text: "Meridian Cap — Discovery Call" },
      { type: "meta", text: "15-May-2026 10:30 ET · 32 min · Zoom" },
      { type: "h2", text: "Attendees" },
      { type: "ul", items: [
        "Sara Voss — Head of Research, Meridian Cap",
        "Daniel Wu — PM, US Equities",
        "Marcus Liu (us) — Sr. Analyst, Semis & SaaS",
      ]},
      { type: "h2", text: "Context" },
      { type: "p", text: "Meridian is repositioning the US book into AI infra. ~$2.1B AUM; current semis exposure 14%. Looking for differentiated research, not consensus. Sara has been burned by sell-side templated PTs." },
      { type: "h2", text: "What they want" },
      { type: "ul", items: [
        "Weekly thematic memos — short, opinionated",
        "Access to scenario models, not just final PT",
        "Quarterly deep-dive on one name from our coverage",
      ]},
    ],
  },
  {
    id: "N-0140",
    title: "DCF Model Assumptions — Semis FY26",
    type: "reference",
    tags: ["DCF", "Sector/Semis", "Q4-25"],
    pinned: false,
    updated: "2026-05-13T16:51:00",
    created: "2026-04-22T09:00:00",
    author: "ML",
    wordCount: 2104,
    actionItems: [],
    body: [
      { type: "h1", text: "DCF Model Assumptions — Semis FY26" },
      { type: "meta", text: "Last revised 13-May-2026 · Owner ML · Source-of-truth for sector models" },
      { type: "p", text: "Canonical inputs for all DCF models across semis coverage. Override only with note and rationale." },
    ],
  },
  {
    id: "N-0139",
    title: "Sector Comp — AI Infra Pure-Plays",
    type: "analysis",
    tags: ["Comps", "Sector/Semis"],
    pinned: false,
    updated: "2026-05-12T18:22:00",
    created: "2026-05-12T15:00:00",
    author: "ML",
    wordCount: 945,
    actionItems: [
      { id: "c1", text: "Refresh table after MRVL print 22-May", done: false, due: "2026-05-23", owner: "ML" },
    ],
    body: [
      { type: "h1", text: "Sector Comp — AI Infra Pure-Plays" },
      { type: "meta", text: "12-May-2026 · 6 names · Source: company filings + FactSet" },
    ],
  },
  {
    id: "N-0138",
    title: "Weekly Review — W19",
    type: "quick",
    tags: ["Internal"],
    pinned: false,
    updated: "2026-05-11T17:45:00",
    created: "2026-05-11T17:30:00",
    author: "ML",
    wordCount: 312,
    actionItems: [],
    body: [
      { type: "h1", text: "Weekly Review — W19" },
      { type: "p", text: "Slow week on prints. Spent Tue–Thu on the MeridianCap pitch deck." },
    ],
  },
  {
    id: "N-0137",
    title: "Client A — SaaS Coverage Initiation Memo",
    type: "project",
    tags: ["ClientA", "Sector/SaaS", "Memo"],
    pinned: false,
    updated: "2026-05-09T13:18:00",
    created: "2026-05-02T10:00:00",
    author: "ML",
    wordCount: 3201,
    actionItems: [
      { id: "d1", text: "Draft section 4 (competitive moat)", done: true, due: "2026-05-08", owner: "ML" },
      { id: "d2", text: "Internal review w/ JK", done: false, due: "2026-05-19", owner: "JK" },
    ],
    body: [
      { type: "h1", text: "SaaS Coverage Initiation — Client A" },
      { type: "meta", text: "Draft v3 · 9-May-2026 · 28 pp" },
    ],
  },
  {
    id: "N-0136",
    title: "Quick — Rate cut path implied by Fed dots",
    type: "quick",
    tags: ["Internal"],
    pinned: false,
    updated: "2026-05-08T09:12:00",
    created: "2026-05-08T09:11:00",
    author: "ML",
    wordCount: 84,
    actionItems: [],
    body: [
      { type: "h1", text: "Rate cut path implied by Fed dots" },
      { type: "p", text: "SEP median: 2 cuts CY26, 3 cuts CY27. Markets price 3 / 4. Spread = upside surprise on duration if Fed delivers fewer." },
    ],
  },
  {
    id: "N-0135",
    title: "Reading list — 2026 H1",
    type: "reference",
    tags: ["Internal"],
    pinned: false,
    updated: "2026-05-06T20:11:00",
    created: "2026-04-01T09:00:00",
    author: "ML",
    wordCount: 540,
    actionItems: [],
    body: [{ type: "h1", text: "Reading list — 2026 H1" }],
  },
  {
    id: "N-0134",
    title: "TechCorp — Pre-print scenarios",
    type: "analysis",
    tags: ["TechCorp", "Q3-25", "Earnings"],
    pinned: false,
    updated: "2026-05-13T22:08:00",
    created: "2026-05-13T20:00:00",
    author: "ML",
    wordCount: 1120,
    actionItems: [],
    body: [{ type: "h1", text: "TechCorp — Pre-print scenarios" }],
  },
  {
    id: "N-0133",
    title: "Conf notes — Goldman TMT 6-May",
    type: "meeting",
    tags: ["Sector/Semis", "Sector/SaaS"],
    pinned: false,
    updated: "2026-05-06T18:00:00",
    created: "2026-05-06T08:00:00",
    author: "ML",
    wordCount: 2240,
    actionItems: [],
    body: [{ type: "h1", text: "Goldman TMT Conf — Day 1+2" }],
  },
  {
    id: "N-0132",
    title: "Idea — Long/short basket: AI capex beneficiaries vs hyperscaler suppliers under-earning",
    type: "quick",
    tags: ["Internal", "Sector/Semis"],
    pinned: false,
    updated: "2026-05-04T11:22:00",
    created: "2026-05-04T11:21:00",
    author: "ML",
    wordCount: 156,
    actionItems: [],
    body: [{ type: "h1", text: "L/S basket: capex bens vs underearners" }],
  },
  {
    id: "N-0131",
    title: "SWOT — Project Helios pitch",
    type: "project",
    tags: ["Internal"],
    pinned: false,
    updated: "2026-05-01T16:00:00",
    created: "2026-05-01T15:30:00",
    author: "ML",
    wordCount: 780,
    actionItems: [],
    body: [{ type: "h1", text: "SWOT — Project Helios" }],
  },
];

window.SAMPLE_TEMPLATES = [
  {
    id: "tpl-earnings",
    name: "Earnings Review",
    icon: "▤",
    desc: "Print recap, table, valuation impact, PT delta",
    type: "analysis",
    sections: ["Headline", "The print", "Why it matters", "Valuation", "PT change"],
    usedCount: 47,
  },
  {
    id: "tpl-meeting",
    name: "Client Meeting",
    icon: "◇",
    desc: "Attendees, context, what they want, next steps",
    type: "meeting",
    sections: ["Attendees", "Context", "What they want", "Action items"],
    usedCount: 31,
  },
  {
    id: "tpl-dcf",
    name: "DCF Model Brief",
    icon: "∑",
    desc: "Assumptions table, sensitivity, output range",
    type: "analysis",
    sections: ["Assumptions", "Sensitivity grid", "Implied EV", "Risk factors"],
    usedCount: 22,
  },
  {
    id: "tpl-swot",
    name: "SWOT",
    icon: "◫",
    desc: "Four-quadrant — strengths, weaknesses, opportunities, threats",
    type: "project",
    sections: ["Strengths", "Weaknesses", "Opportunities", "Threats"],
    usedCount: 14,
  },
  {
    id: "tpl-weekly",
    name: "Weekly Review",
    icon: "≡",
    desc: "What I shipped, what I learned, next week",
    type: "quick",
    sections: ["Shipped", "Learned", "Blocked", "Next week"],
    usedCount: 19,
  },
  {
    id: "tpl-memo",
    name: "Coverage Memo",
    icon: "▥",
    desc: "Long-form initiation or update memo",
    type: "project",
    sections: ["Thesis", "Business", "Numbers", "Valuation", "Risks"],
    usedCount: 8,
  },
  {
    id: "tpl-comp",
    name: "Sector Comp",
    icon: "▦",
    desc: "Comparable companies, multiples, growth",
    type: "analysis",
    sections: ["Universe", "Multiples table", "Growth vs multiple", "Conclusion"],
    usedCount: 26,
  },
  {
    id: "tpl-blank",
    name: "Blank note",
    icon: "□",
    desc: "Start from scratch",
    type: "quick",
    sections: [],
    usedCount: 184,
  },
];

window.TYPE_LABELS = {
  quick: "QUICK",
  meeting: "MEETING",
  project: "PROJECT",
  analysis: "ANALYSIS",
  reference: "REFERENCE",
};

window.TAG_COLORS = {
  blue:   { fg: "oklch(0.45 0.10 250)", bg: "oklch(0.95 0.03 250)", fgDark: "oklch(0.78 0.10 250)", bgDark: "oklch(0.28 0.06 250)" },
  violet: { fg: "oklch(0.45 0.10 295)", bg: "oklch(0.95 0.03 295)", fgDark: "oklch(0.78 0.10 295)", bgDark: "oklch(0.28 0.06 295)" },
  amber:  { fg: "oklch(0.45 0.10 70)",  bg: "oklch(0.95 0.04 70)",  fgDark: "oklch(0.80 0.10 70)",  bgDark: "oklch(0.30 0.06 70)" },
  green:  { fg: "oklch(0.45 0.10 150)", bg: "oklch(0.95 0.03 150)", fgDark: "oklch(0.78 0.10 150)", bgDark: "oklch(0.28 0.06 150)" },
  rose:   { fg: "oklch(0.50 0.10 20)",  bg: "oklch(0.95 0.03 20)",  fgDark: "oklch(0.80 0.10 20)",  bgDark: "oklch(0.30 0.06 20)" },
  gray:   { fg: "oklch(0.40 0.005 250)", bg: "oklch(0.94 0.003 250)", fgDark: "oklch(0.75 0.005 250)", bgDark: "oklch(0.28 0.003 250)" },
};

window.tagColor = function(name) {
  const tag = window.SAMPLE_TAGS.find(t => t.name === name);
  return tag ? tag.color : "gray";
};
