// Sample data — financial analyst / consultant scenario
// All notes belong to "Lena Park, Senior Analyst, Holloway Capital Advisors"

window.SEED = (() => {
  const today = new Date('2026-05-17');
  const fmt = (d) => d.toISOString().slice(0, 10);
  const daysAgo = (n) => { const d = new Date(today); d.setDate(d.getDate() - n); return d; };
  const daysAhead = (n) => { const d = new Date(today); d.setDate(d.getDate() + n); return d; };

  const tags = [
    { id: 'q3-26', label: 'q3-2026', hue: 210 },
    { id: 'q2-26', label: 'q2-2026', hue: 210 },
    { id: 'client-meridian', label: 'meridian-foods', hue: 12 },
    { id: 'client-arclight', label: 'arclight-energy', hue: 38 },
    { id: 'client-northwind', label: 'northwind-logistics', hue: 152 },
    { id: 'sector-cpg', label: 'sector/cpg', hue: 282 },
    { id: 'sector-energy', label: 'sector/energy', hue: 38 },
    { id: 'sector-logistics', label: 'sector/logistics', hue: 152 },
    { id: 'thesis', label: 'thesis', hue: 0 },
    { id: 'due-dilly', label: 'due-diligence', hue: 248 },
    { id: 'internal', label: 'internal', hue: 0, sat: 0 },
    { id: 'memo', label: 'memo', hue: 0, sat: 0 },
  ];

  const notes = [
    {
      id: 'n-001',
      title: 'Meridian Foods — Q2 deep-dive',
      type: 'analysis',
      tags: ['client-meridian', 'sector-cpg', 'q2-26', 'due-dilly'],
      updated: daysAgo(0),
      created: daysAgo(11),
      pinned: true,
      backlinks: ['n-004', 'n-009'],
      blocks: [
        { t: 'h1', text: 'Meridian Foods — Q2 deep-dive' },
        { t: 'meta' },
        { t: 'callout', tone: 'thesis', text: 'Margin compression is cyclical, not structural. Reiterate BUY at $42 PT, downside $31, upside $58.' },
        { t: 'h2', text: 'Segment performance' },
        { t: 'table', headers: ['Segment', 'Q2 rev ($M)', 'YoY %', 'GM %', 'Op inc ($M)'],
          rows: [
            ['Branded grocery',  '412.3', '+4.1', '38.2', '78.4'],
            ['Foodservice',      '188.7', '+11.6', '22.4', '21.1'],
            ['Private label',    ' 91.2', '-2.3', '14.9', ' 6.0'],
            ['International',    '134.5', '+7.8', '29.1', '24.9'],
          ],
          sum: [true, true, false, false, true] },
        { t: 'h2', text: 'Action items' },
        { t: 'action', text: 'Reconcile foodservice GM bridge with IR commentary', owner: 'LP', due: daysAhead(2), done: false },
        { t: 'action', text: 'Pull SKU-level data from Numerator before Thursday call', owner: 'RK', due: daysAhead(1), done: true },
        { t: 'action', text: 'Draft 1-pager for IC — focus on private label drag', owner: 'LP', due: daysAhead(5), done: false },
        { t: 'h2', text: 'Notes from IR call' },
        { t: 'p', text: 'CFO flagged commodity reset already priced in — wheat down 14% QoQ. Mgmt guiding to 50bps GM expansion in H2; consensus baking in 35bps. Buyback pace held at $80M/quarter, ~3.1% yield support.' },
        { t: 'p', text: 'See related: [[Northwind logistics — freight read-through]] and [[CPG sector — Q2 wrap]].' },
      ],
    },
    {
      id: 'n-002',
      title: 'IC weekly — May 12',
      type: 'meeting',
      tags: ['internal', 'memo', 'q2-26'],
      updated: daysAgo(5),
      created: daysAgo(5),
      pinned: true,
      blocks: [
        { t: 'h1', text: 'IC weekly — May 12' },
        { t: 'meta' },
        { t: 'attendees', list: ['Lena Park (chair)', 'Daniel Holloway', 'Rashmi Kapoor', 'Tom Vasquez', 'Priya Anand'] },
        { t: 'h2', text: 'Agenda' },
        { t: 'list', items: ['Portfolio review — top 5 conviction names', 'Meridian Foods Q2 prep', 'Arclight Energy thesis check-in', 'Q3 sector allocation draft'] },
        { t: 'h2', text: 'Decisions' },
        { t: 'list', items: ['Trim Northwind by 75bps; redeploy to Meridian on weakness <$38', 'Hold Arclight until Permian acreage clarity (Q3 earnings)', 'Approve new template for sector memos — Priya owns'] },
        { t: 'h2', text: 'Action items' },
        { t: 'action', text: 'Update conviction sheet by EOD Wed', owner: 'LP', due: daysAgo(3), done: true },
        { t: 'action', text: 'Send Meridian pre-read to IC', owner: 'LP', due: daysAhead(1), done: false },
        { t: 'action', text: 'Circulate Q3 sector draft', owner: 'PA', due: daysAhead(4), done: false },
      ],
    },
    {
      id: 'n-003',
      title: 'Arclight Energy — Permian thesis',
      type: 'project',
      tags: ['client-arclight', 'sector-energy', 'thesis'],
      updated: daysAgo(1),
      created: daysAgo(34),
      pinned: true,
      blocks: [
        { t: 'h1', text: 'Arclight Energy — Permian thesis' },
        { t: 'meta' },
        { t: 'callout', tone: 'thesis', text: 'Acreage in Midland sub-basin is mispriced by ~$1.4B vs. comps. Catalyst: Q3 well productivity disclosure.' },
        { t: 'h2', text: 'Key economics' },
        { t: 'table', headers: ['Metric', 'Arclight', 'Peer median', 'Δ'],
          rows: [
            ['Net acres (Midland)', '184k', '142k', '+30%'],
            ['Type curve EUR (Mboe)', '1,180', '1,040', '+13%'],
            ['Break-even ($/bbl)', ' 41', ' 48', '-15%'],
            ['Net debt / EBITDA', '0.9x', '1.4x', '-36%'],
          ] },
        { t: 'h2', text: 'Risks' },
        { t: 'list', items: ['Commodity beta — assume $65 WTI floor', 'Regulatory drag on flaring permits', 'Management track record on capital returns is short (2 yrs)'] },
      ],
    },
    {
      id: 'n-004',
      title: 'CPG sector — Q2 wrap',
      type: 'reference',
      tags: ['sector-cpg', 'q2-26'],
      updated: daysAgo(2),
      created: daysAgo(8),
      pinned: false,
      blocks: [
        { t: 'h1', text: 'CPG sector — Q2 wrap' },
        { t: 'meta' },
        { t: 'p', text: 'Cross-cut of 14 large-cap CPG names reporting Q2. Theme: volume returning, price taking pause, GM recovering ~40-60bps off trough.' },
        { t: 'table', headers: ['Name', 'Vol YoY', 'Price YoY', 'GM bps Δ'],
          rows: [
            ['Meridian',  '+1.8', '+2.3', '+45'],
            ['Cascade',   '+0.4', '+3.1', '+12'],
            ['Brightleaf', '-0.9', '+4.4', '-8'],
            ['Hartford',  '+2.6', '+0.9', '+62'],
            ['Northcup',  '+3.1', '-0.4', '+71'],
          ] },
      ],
    },
    {
      id: 'n-005',
      title: 'Meeting — Meridian IR, 05/16',
      type: 'meeting',
      tags: ['client-meridian', 'sector-cpg'],
      updated: daysAgo(1),
      created: daysAgo(1),
      pinned: false,
      blocks: [
        { t: 'h1', text: 'Meeting — Meridian IR, 05/16' },
        { t: 'meta' },
        { t: 'attendees', list: ['Lena Park', 'Rashmi Kapoor', 'Sarah Chen (Meridian IR)', 'Marcus Webb (Meridian CFO)'] },
        { t: 'list', items: ['Confirmed buyback pace ($80M/qtr)', 'Foodservice channel mix shift = real, not optical', 'Private label drag expected to anniversary by Q4'] },
        { t: 'action', text: 'Get foodservice contract durations from IR', owner: 'RK', due: daysAhead(3), done: false },
      ],
    },
    {
      id: 'n-006',
      title: 'Northwind Logistics — freight read-through',
      type: 'project',
      tags: ['client-northwind', 'sector-logistics'],
      updated: daysAgo(3),
      created: daysAgo(21),
      pinned: false,
      blocks: [
        { t: 'h1', text: 'Northwind Logistics — freight read-through' },
        { t: 'meta' },
        { t: 'p', text: 'Trim signal triggered by truckload spot rates rolling over -8% MoM. Position sized for cycle, not secular.' },
        { t: 'action', text: 'Set price alert at $24.50 (cost basis)', owner: 'LP', due: daysAhead(0), done: false },
      ],
    },
    {
      id: 'n-007',
      title: 'Quick — rates print reaction',
      type: 'quick',
      tags: ['internal'],
      updated: daysAgo(0),
      created: daysAgo(0),
      pinned: false,
      blocks: [
        { t: 'h1', text: 'Quick — rates print reaction' },
        { t: 'p', text: 'Core CPI 0.21 vs 0.28e. Curve bull-flattened 6bps. Watch consumer staples reaction — Meridian should benefit from disinflation narrative.' },
      ],
    },
    {
      id: 'n-008',
      title: 'Weekly review — wk 20',
      type: 'reference',
      tags: ['internal'],
      updated: daysAgo(4),
      created: daysAgo(4),
      pinned: false,
      blocks: [
        { t: 'h1', text: 'Weekly review — wk 20' },
        { t: 'h2', text: 'What worked' },
        { t: 'list', items: ['Meridian sized up at $36.20 — +6.4% on the week', 'Caught the freight rollover before sell-side notes'] },
        { t: 'h2', text: 'What didn\u2019t' },
        { t: 'list', items: ['Held Arclight through last week\u2019s drawdown — should have hedged via XOP', 'Missed the small-cap CPG short on Brightleaf'] },
      ],
    },
    {
      id: 'n-009',
      title: 'Meridian — model assumptions v3',
      type: 'analysis',
      tags: ['client-meridian', 'sector-cpg', 'due-dilly'],
      updated: daysAgo(2),
      created: daysAgo(14),
      pinned: false,
      blocks: [
        { t: 'h1', text: 'Meridian — model assumptions v3' },
        { t: 'meta' },
        { t: 'table', headers: ['Line', '2024A', '2025E', '2026E', '2027E'],
          rows: [
            ['Revenue ($M)',     '3,142', '3,289', '3,478', '3,672'],
            ['Gross margin %',   ' 31.8', ' 32.4', ' 33.1', ' 33.6'],
            ['Op margin %',      ' 12.1', ' 12.8', ' 13.4', ' 13.8'],
            ['FCF ($M)',         '  284', '  318', '  362', '  401'],
          ] },
      ],
    },
    {
      id: 'n-010',
      title: 'Reference — IC memo template usage',
      type: 'reference',
      tags: ['internal', 'memo'],
      updated: daysAgo(9),
      created: daysAgo(9),
      pinned: false,
      blocks: [
        { t: 'h1', text: 'Reference — IC memo template usage' },
        { t: 'p', text: 'House style for investment committee memos. Lead with thesis in one sentence, three bullets max for the why, then numbers, then risks. No more than two pages.' },
      ],
    },
    {
      id: 'n-011',
      title: 'Quick — Brightleaf 8-K skim',
      type: 'quick',
      tags: ['sector-cpg'],
      updated: daysAgo(6),
      created: daysAgo(6),
      pinned: false,
      blocks: [
        { t: 'h1', text: 'Quick — Brightleaf 8-K skim' },
        { t: 'p', text: 'CFO transition. Interim from inside. No restatement. Watch for guide pull on next print.' },
      ],
    },
    {
      id: 'n-012',
      title: 'Q3 sector allocation — draft',
      type: 'project',
      tags: ['q3-26', 'internal', 'thesis'],
      updated: daysAgo(7),
      created: daysAgo(7),
      pinned: false,
      blocks: [
        { t: 'h1', text: 'Q3 sector allocation — draft' },
        { t: 'meta' },
        { t: 'table', headers: ['Sector', 'Curr %', 'Target %', 'Δ bps'],
          rows: [
            ['CPG',        '14.2', '16.5', '+230'],
            ['Energy',     '11.8', '13.0', '+120'],
            ['Logistics',  ' 8.4', ' 6.5', '-190'],
            ['Financials', '12.1', '12.0', ' -10'],
            ['Tech',       '21.7', '20.0', '-170'],
          ] },
      ],
    },
  ];

  const templates = [
    { id: 't-meeting', name: 'Meeting notes', type: 'meeting', desc: 'Attendees, agenda, decisions, action items', usage: 142, blocks: [
      { t: 'h1', text: 'Meeting — [topic], [date]' },
      { t: 'meta' },
      { t: 'attendees', list: ['', '', ''] },
      { t: 'h2', text: 'Agenda' },
      { t: 'list', items: ['', '', ''] },
      { t: 'h2', text: 'Decisions' },
      { t: 'list', items: [''] },
      { t: 'h2', text: 'Action items' },
      { t: 'action', text: '', owner: '', due: null, done: false },
    ] },
    { id: 't-project', name: 'Project brief', type: 'project', desc: 'Thesis, scope, milestones, risks', usage: 88, blocks: [
      { t: 'h1', text: '[Project / client] — brief' },
      { t: 'meta' },
      { t: 'callout', tone: 'thesis', text: 'One-line thesis here.' },
      { t: 'h2', text: 'Scope' }, { t: 'p', text: '' },
      { t: 'h2', text: 'Milestones' }, { t: 'list', items: [''] },
      { t: 'h2', text: 'Risks' }, { t: 'list', items: [''] },
    ] },
    { id: 't-finsum', name: 'Financial summary', type: 'analysis', desc: 'P&L table, KPI bridge, valuation snap', usage: 211, blocks: [
      { t: 'h1', text: '[Ticker] — financial summary' },
      { t: 'meta' },
      { t: 'table', headers: ['Line', 'PY', 'CY', 'YoY %'], rows: [['Revenue', '', '', ''], ['Gross profit', '', '', ''], ['Op income', '', '', ''], ['Net income', '', '', '']] },
    ] },
    { id: 't-swot', name: 'SWOT', type: 'analysis', desc: '2×2 grid — strengths / weaknesses / opportunities / threats', usage: 47, blocks: [
      { t: 'h1', text: '[Subject] — SWOT' },
      { t: 'swot' },
    ] },
    { id: 't-weekly', name: 'Weekly review', type: 'reference', desc: 'What worked, what didn\u2019t, next week', usage: 96, blocks: [
      { t: 'h1', text: 'Weekly review — wk [NN]' },
      { t: 'h2', text: 'What worked' }, { t: 'list', items: [''] },
      { t: 'h2', text: 'What didn\u2019t' }, { t: 'list', items: [''] },
      { t: 'h2', text: 'Next week' }, { t: 'list', items: [''] },
    ] },
    { id: 't-1on1', name: '1:1', type: 'meeting', desc: 'Recurring 1:1 with direct report', usage: 38, blocks: [
      { t: 'h1', text: '1:1 with [name], [date]' },
      { t: 'h2', text: 'Their topics' }, { t: 'list', items: [''] },
      { t: 'h2', text: 'My topics' }, { t: 'list', items: [''] },
      { t: 'h2', text: 'Follow-ups' }, { t: 'action', text: '', owner: '', due: null, done: false },
    ] },
    { id: 't-dd', name: 'Due diligence checklist', type: 'analysis', desc: 'Standardized DD across business / financials / risks', usage: 64, blocks: [
      { t: 'h1', text: '[Target] — due diligence' },
      { t: 'h2', text: 'Business' }, { t: 'list', items: ['', '', ''] },
      { t: 'h2', text: 'Financials' }, { t: 'list', items: ['', '', ''] },
      { t: 'h2', text: 'Risks' }, { t: 'list', items: ['', '', ''] },
    ] },
    { id: 't-quick', name: 'Quick note', type: 'quick', desc: 'Blank canvas, no structure', usage: 412, blocks: [{ t: 'h1', text: '' }, { t: 'p', text: '' }] },
  ];

  return { notes, tags, templates, today, fmt };
})();
